name: release

on:
  push:
    branches:
      - master
      - beta

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Node.js and semantic-release plugins
      uses: actions/setup-node@v1
      with:
        node-version: 16.15.0
    - run: npm install -g semantic-release@18.0.1 @semantic-release/github@8.0.4 @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/exec semantic-release/git semantic-release/release-notes-generator
    - run: mvn package
    - name: Release
      run: npx semantic-release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}